# Generated by Django 2.1.1 on 2018-09-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_author', models.CharField(max_length=50)),
                ('tweet_txt', models.CharField(max_length=50)),
                ('tweet_date', models.DateTimeField()),
            ],
        ),
    ]
