# Generated by Django 2.1.1 on 2018-09-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20180930_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_date',
        ),
    ]
